Repository prgrms-web-devcourse-final-project/WEB1_2_BUMBLEBEE_BE, pull requests merged in 2024-12, with the labels that each got.

#127 Feature/#121 member review fefactor
  src/main/java/roomit/main/domain/member/controller/MemberController.java
  src/main/java/roomit/main/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/roomit/main/domain/member/entity/Age.java
  src/main/java/roomit/main/domain/member/entity/Member.java
  src/main/java/roomit/main/domain/member/entity/value/MemberEmail.java
  src/main/java/roomit/main/domain/member/service/MemberService.java
  src/main/java/roomit/main/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/roomit/main/domain/review/controller/ReviewController.java
  src/main/java/roomit/main/domain/review/dto/request/ReviewRegisterRequest.java
  src/main/java/roomit/main/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/roomit/main/domain/review/dto/response/ReviewResponse.java
  src/main/java/roomit/main/domain/review/entity/Review.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/domain/studyroom/dto/response/FindPossibleStudyRoomResponse.java
  src/main/java/roomit/main/domain/workplace/repository/WorkplaceRepository.java
  src/main/java/roomit/main/global/controller/FileUploadController.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/main/java/roomit/main/global/service/FileUploadService.java
  src/test/java/roomit/main/domain/member/controller/MemberControllerTest.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/main/domain/review/service/ReviewServiceTest.java
Labels: 🔨 Refactor

#129 Refactor/ Workplace, Review refactor
  src/main/java/roomit/main/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/roomit/main/domain/review/dto/response/ReviewResponse.java
  src/main/java/roomit/main/domain/review/entity/Review.java
  src/main/java/roomit/main/domain/workplace/controller/WorkplaceController.java
  src/main/java/roomit/main/domain/workplace/entity/Workplace.java
  src/main/java/roomit/main/domain/workplace/entity/value/Coordinate.java
Labels: 🔨 Refactor

#130 Refactor/#110 refactor chat & 멘토링 코드리뷰
  build.gradle
  src/main/java/roomit/main/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/roomit/main/domain/chat/chatmessage/dto/ChatMessageRequest.java
  src/main/java/roomit/main/domain/chat/chatmessage/dto/ChatMessageResponse.java
  src/main/java/roomit/main/domain/chat/chatmessage/entity/ChatMessage.java
  src/main/java/roomit/main/domain/chat/chatmessage/repository/ChatMessageRepository.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatMessageBatchProcessor.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/roomit/main/domain/chat/chatroom/repositoroy/ChatRoomRepository.java
  src/main/java/roomit/main/domain/chat/dto/ChatMessageRequest.java
  src/main/java/roomit/main/domain/chat/dto/ChatMessageResponse.java
  src/main/java/roomit/main/domain/chat/redis/controller/RedisController.java
  src/main/java/roomit/main/domain/chat/redis/service/RedisLuaService.java
  src/main/java/roomit/main/domain/chat/redis/service/RedisPublisher.java
  src/main/java/roomit/main/domain/chat/redis/service/RedisSubscriber.java
  src/main/java/roomit/main/domain/chat/service/ChatService.java
  src/main/java/roomit/main/domain/chatroom/entity/ChatRoom.java
  src/main/java/roomit/main/domain/chatroom/repositoroy/ChatRoomRepository.java
  src/main/java/roomit/main/domain/workplace/controller/WorkplaceController.java
  src/main/java/roomit/main/domain/workplace/dto/request/WorkplaceGetRequest.java
  src/main/java/roomit/main/domain/workplace/repository/WorkplaceRepository.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/RedisConfig.java
  src/main/java/roomit/main/global/config/chat/JacksonConfig.java
  src/main/java/roomit/main/global/config/chat/ScheduledTasks.java
  src/main/java/roomit/main/global/config/chat/WebSocketConfig.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/test/java/roomit/main/domain/chat/ChatIntegrationTest.java
  src/test/java/roomit/main/domain/chat/RedisPubSubTest.java
  src/test/java/roomit/main/domain/chat/controller/ChatControllerTest.java
  src/test/java/roomit/main/domain/chat/service/ChatServiceTest.java
  src/test/java/roomit/main/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🔨 Refactor

#134 Feature/#121 member review fefactor
  src/main/java/roomit/main/domain/review/controller/ReviewController.java
  src/main/java/roomit/main/domain/review/entity/Review.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/main/java/roomit/main/global/error/ErrorResponse.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/main/domain/review/service/ReviewServiceTest.java
Labels: 🔨 Refactor

#136 :recycle: refactor : reservation refactor
  src/main/java/roomit/main/domain/member/entity/Member.java
  src/main/java/roomit/main/domain/reservation/controller/ReservationController.java
  src/main/java/roomit/main/domain/reservation/dto/request/CreateReservationRequest.java
  src/main/java/roomit/main/domain/reservation/dto/request/UpdateReservationRequest.java
  src/main/java/roomit/main/domain/reservation/dto/response/MyWorkPlaceReservationResponse.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/reservation/entity/ReservationState.java
  src/main/java/roomit/main/domain/reservation/entity/value/ReservationName.java
  src/main/java/roomit/main/domain/reservation/entity/value/ReservationNum.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/domain/review/dto/response/ReviewResponse.java
  src/main/java/roomit/main/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/roomit/main/domain/studyroom/repository/StudyRoomRepository.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/test/java/roomit/main/domain/reservation/controller/ReservationControllerTest.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/main/domain/review/service/ReviewServiceTest.java
Labels: 🔨 Refactor

#139 BugFix / merge 단계에서 전체적인 오류 코드 수정
  src/main/java/roomit/main/domain/business/service/BusinessService.java
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/reservation/dto/response/MyWorkPlaceReservationResponse.java
  src/main/java/roomit/main/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/domain/review/dto/response/ReviewResponse.java
  src/main/java/roomit/main/domain/review/entity/Review.java
  src/main/java/roomit/main/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/domain/studyroom/dto/request/CreateStudyRoomRequest.java
  src/main/java/roomit/main/domain/studyroom/dto/request/StudyRoomRequest.java
  src/main/java/roomit/main/domain/studyroom/dto/request/UpdateStudyRoomRequest.java
  src/main/java/roomit/main/domain/studyroom/dto/response/FindPossibleStudyRoomResponse.java
  src/main/java/roomit/main/domain/studyroom/dto/response/RecentStudyRoomResponse.java
  src/main/java/roomit/main/domain/studyroom/dto/response/StudyRoomResponse.java
  src/main/java/roomit/main/domain/studyroom/entity/StudyRoom.java
  src/main/java/roomit/main/domain/studyroom/entity/value/BaseEntity.java
  src/main/java/roomit/main/domain/studyroom/entity/value/StudyRoomName.java
  src/main/java/roomit/main/domain/studyroom/repository/StudyRoomRepository.java
  src/main/java/roomit/main/domain/studyroom/service/StudyRoomService.java
  src/main/java/roomit/main/domain/workplace/dto/request/WorkplaceRequest.java
  src/main/java/roomit/main/domain/workplace/entity/Workplace.java
  src/main/java/roomit/main/domain/workplace/entity/value/ImageUrl.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/controller/ExceptionController.java
  src/main/java/roomit/main/global/controller/FileUploadController.java
  src/main/java/roomit/main/global/error/ErrorResponse.java
  src/main/java/roomit/main/global/inner/AwsProperties.java
  src/main/java/roomit/main/global/inner/ImageUrl.java
  src/main/java/roomit/main/global/oauth2/config/CustomSuccessHandler.java
  src/main/java/roomit/main/global/service/FileUploadService.java
  src/main/java/roomit/main/global/service/ImageService.java
  src/main/java/roomit/main/global/token/config/JWTFilter.java
  src/main/java/roomit/main/global/token/config/JWTUtil.java
  src/main/java/roomit/main/global/token/config/LogoutFilter.java
  src/main/java/roomit/main/global/token/controller/LoginController.java
  src/main/java/roomit/main/global/token/controller/ReissueController.java
  src/main/java/roomit/main/global/token/entity/RefreshEntity.java
  src/main/java/roomit/main/global/token/service/TokenService.java
  src/test/java/roomit/main/domain/business/controller/BusinessControllerTest.java
  src/test/java/roomit/main/domain/chat/RedisPubSubTest.java
  src/test/java/roomit/main/domain/chat/WebSocketTest.java
  src/test/java/roomit/main/domain/member/controller/MemberControllerTest.java
  src/test/java/roomit/main/domain/reservation/controller/ReservationControllerTest.java
  src/test/java/roomit/main/domain/reservation/service/ReservationServiceTest.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/main/domain/review/service/ReviewServiceTest.java
  src/test/java/roomit/main/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🐞 BugFix

#141 :recycle: refactor : Reservation Refactor
  src/main/java/roomit/main/domain/reservation/controller/ReservationController.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/error/ErrorCode.java
Labels: 🔨 Refactor

#144 :bug: fix : 변수명 수정으로 인한 결제 버그 수정
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/global/error/ErrorCode.java
Labels: 🐞 BugFix

#146 🐞 : bugfix : Reservation bugfix
  src/main/java/roomit/main/domain/reservation/controller/ReservationController.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/global/error/ErrorCode.java
Labels: 🐞 BugFix

#148 Feature/#95 collaborative filtering
  src/main/java/roomit/main/global/config/security/CorsMvcConfig.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/recomend/RecommendationController.java
  src/main/java/roomit/main/global/recomend/RecommendationService.java
  src/main/java/roomit/main/global/token/config/JWTFilter.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
Labels: ✨ Feature

#150 :sparkles: feat : 리프레시 토큰 Redis 저장
  src/main/java/roomit/main/global/config/RedisConfig.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/token/config/LogoutFilter.java
  src/main/java/roomit/main/global/token/entity/Refresh.java
  src/main/java/roomit/main/global/token/entity/RefreshEntity.java
  src/main/java/roomit/main/global/token/repository/RefreshRepository.java
  src/main/java/roomit/main/global/token/service/TokenService.java
Labels: ✨ Feature

#151 Refactor/#131 studyroom CRUD 전체적인 수정
  src/main/java/roomit/main/domain/business/repository/BusinessRepository.java
  src/main/java/roomit/main/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/domain/review/dto/request/ReviewRegisterRequest.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/domain/studyroom/controller/StudyRoomController.java
  src/main/java/roomit/main/domain/studyroom/dto/request/CreateStudyRoomRequest.java
  src/main/java/roomit/main/domain/studyroom/dto/request/FindAvailableStudyRoomRequest.java
  src/main/java/roomit/main/domain/studyroom/dto/request/StudyRoomRequest.java
  src/main/java/roomit/main/domain/studyroom/dto/request/UpdateStudyRoomRequest.java
  src/main/java/roomit/main/domain/studyroom/dto/response/FindPossibleStudyRoomResponse.java
  src/main/java/roomit/main/domain/studyroom/dto/response/RecentStudyRoomResponse.java
  src/main/java/roomit/main/domain/studyroom/dto/response/ReservationPossibleStudyRoomResponse.java
  src/main/java/roomit/main/domain/studyroom/dto/response/StudyRoomListResponse.java
  src/main/java/roomit/main/domain/studyroom/dto/response/StudyRoomResponse.java
  src/main/java/roomit/main/domain/studyroom/entity/StudyRoom.java
  src/main/java/roomit/main/domain/studyroom/repository/StudyRoomRepository.java
  src/main/java/roomit/main/domain/studyroom/repository/search/SearchStudyRoom.java
  src/main/java/roomit/main/domain/studyroom/repository/search/SearchStudyRoomImpl.java
  src/main/java/roomit/main/domain/studyroom/service/StudyRoomService.java
  src/main/java/roomit/main/domain/workplace/dto/response/DistanceWorkplaceResponse.java
  src/main/java/roomit/main/domain/workplace/repository/WorkplaceRepository.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/controller/FileController.java
  src/main/java/roomit/main/global/controller/FileUploadController.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/main/java/roomit/main/global/oauth2/controller/Oauth2Controller.java
  src/main/java/roomit/main/global/recomend/RecommendationController.java
  src/main/java/roomit/main/global/recomend/RecommendationService.java
  src/main/java/roomit/main/global/service/FileLocationService.java
  src/main/java/roomit/main/global/service/FileUploadService.java
  src/main/java/roomit/main/global/token/config/JWTFilter.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/main/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#152 ✨ feat : 결제 취소 추가 및 검증 요청 리팩토링
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/payments/config/PaymentsConfig.java
  src/main/java/roomit/main/domain/payments/controller/PaymentsRestController.java
  src/main/java/roomit/main/domain/payments/dto/response/PaymentValidationResponse.java
  src/main/java/roomit/main/domain/payments/dto/response/PaymentsResponse.java
  src/main/java/roomit/main/domain/payments/dto/response/PaymentsSuccessResponse.java
  src/main/java/roomit/main/domain/payments/entity/Payments.java
  src/main/java/roomit/main/domain/payments/repository/PaymentsRepository.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/global/error/ErrorCode.java
Labels: ✨ Feature

#156 🐛 fix : 예약, 리뷰 수정사항
  src/main/java/roomit/main/domain/reservation/dto/request/CreateReservationRequest.java
  src/main/java/roomit/main/domain/reservation/dto/response/MyWorkPlaceReservationResponse.java
  src/main/java/roomit/main/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/review/dto/response/ReviewResponse.java
  src/main/java/roomit/main/domain/review/entity/Review.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/main/domain/review/service/ReviewServiceTest.java
Labels: 🐞 BugFix

#159 :white_check_mark: Test : 결제 테스트
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/payments/controller/PaymentsRestController.java
  src/main/java/roomit/main/domain/payments/dto/request/PaymentsRequest.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/token/config/JWTFilter.java
  src/test/java/roomit/main/domain/payments/controller/PaymentsControllerTest.java
  src/test/java/roomit/main/domain/payments/service/PaymentsServiceTest.java
Labels: ✅ Test

#163 Refactor/#154 presignedurl
  src/main/java/roomit/main/domain/business/dto/response/BusinessResponse.java
  src/main/java/roomit/main/domain/payments/controller/PaymentsRestController.java
  src/main/java/roomit/main/domain/payments/dto/request/PaymentsRequest.java
  src/main/java/roomit/main/domain/payments/dto/response/PaymentValidationResponse.java
  src/main/java/roomit/main/domain/reservation/controller/ReservationController.java
  src/main/java/roomit/main/domain/reservation/dto/request/UpdateReservationRequest.java
  src/main/java/roomit/main/domain/reservation/dto/response/MyWorkPlaceReservationResponse.java
  src/main/java/roomit/main/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/domain/review/dto/response/ReviewResponse.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/domain/studyroom/controller/StudyRoomController.java
  src/main/java/roomit/main/domain/studyroom/dto/request/CreateStudyRoomRequest.java
  src/main/java/roomit/main/domain/studyroom/dto/response/FindPossibleStudyRoomResponse.java
  src/main/java/roomit/main/domain/studyroom/dto/response/StudyRoomListResponse.java
  src/main/java/roomit/main/domain/studyroom/entity/StudyRoom.java
  src/main/java/roomit/main/domain/studyroom/service/StudyRoomService.java
  src/main/java/roomit/main/domain/workplace/controller/WorkplaceController.java
  src/main/java/roomit/main/domain/workplace/dto/request/WorkplaceRequest.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceCreateResponse.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceDetailResponse.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceResponse.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/RedisConfig.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/config/security/util/CookieUtil.java
  src/main/java/roomit/main/global/controller/FileController.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/main/java/roomit/main/global/inner/ImageUrl.java
  src/main/java/roomit/main/global/service/FileLocationService.java
  src/test/java/roomit/main/domain/business/controller/BusinessControllerTest.java
  src/test/java/roomit/main/domain/business/service/BusinessServiceTest.java
  src/test/java/roomit/main/domain/chat/service/ChatServiceIntegrationTest.java
  src/test/java/roomit/main/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#165 :recycle: refactor : Reservation Refactor
  src/main/java/roomit/main/domain/reservation/dto/response/MyWorkPlaceReservationResponse.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/reservation/entity/ReservationState.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
Labels: 🔨 Refactor

#167 Feature/#149 notification
  http/sub.http
  src/main/java/roomit/main/domain/notification/controller/NotificationController.java
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationDto.java
  src/main/java/roomit/main/domain/notification/entity/Notification.java
  src/main/java/roomit/main/domain/notification/entity/NotificationType.java
  src/main/java/roomit/main/domain/notification/entity/value/NotificationContent.java
  src/main/java/roomit/main/domain/notification/entity/value/RelatedUrl.java
  src/main/java/roomit/main/domain/notification/repository/EmitterRepository.java
  src/main/java/roomit/main/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/roomit/main/domain/notification/repository/NotificationRepository.java
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/domain/review/controller/ReviewController.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/domain/studyroom/repository/StudyRoomRepository.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/error/ErrorCode.java
Labels: ✨ Feature

#166 reactor : 리뷰 응답값,결제 로직, 검색 필터링 수정
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/payments/controller/PaymentsRestController.java
  src/main/java/roomit/main/domain/payments/repository/PaymentsRepository.java
  src/main/java/roomit/main/domain/review/controller/ReviewController.java
  src/main/java/roomit/main/domain/review/dto/response/ReviewMeResponse.java
  src/main/java/roomit/main/domain/review/dto/response/ReviewResponse.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/domain/studyroom/controller/StudyRoomController.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/config/security/util/CookieUtil.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/main/java/roomit/main/global/oauth2/config/CustomSuccessHandler.java
Labels: 🔨 Refactor

#169 Feature/#149 notification
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationDto.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/global/oauth2/config/CustomSuccessHandler.java
Labels: 🔨 Refactor

#171 Refactor/#110 refactor chat
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/ChatRoomBusinessResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/ChatRoomMemberResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/ChatRoomResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/roomit/main/domain/chat/chatroom/repositoroy/ChatRoomRepository.java
  src/main/java/roomit/main/domain/chat/chatroom/service/ChatRoomService.java
  src/test/java/roomit/main/domain/chat/service/ChatServiceIntegrationTest.java
Labels: 🔨 Refactor

#174 feat : 결제 취소 반환값 추가 및 예약 수정사항 적용
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/payments/controller/PaymentsRestController.java
  src/main/java/roomit/main/domain/reservation/controller/ReservationController.java
  src/main/java/roomit/main/domain/reservation/dto/request/CreateReservationRequest.java
  src/main/java/roomit/main/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/test/java/roomit/main/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feature

#177 Refactor/#170 refactor chat redis
  src/main/java/roomit/main/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/roomit/main/domain/chat/chatmessage/dto/ChatMessageResponse.java
  src/main/java/roomit/main/domain/chat/chatmessage/entity/ChatMessage.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/response/ChatRoomBusinessResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/response/ChatRoomDetailsDTO.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/response/ChatRoomMemberResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/response/ChatRoomResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/roomit/main/domain/chat/chatroom/repositoroy/ChatRoomRepository.java
  src/main/java/roomit/main/domain/chat/chatroom/service/ChatRoomService.java
  src/main/java/roomit/main/domain/workplace/entity/Workplace.java
  src/main/java/roomit/main/global/config/chat/SchedulerConfig.java
  src/main/java/roomit/main/global/config/chat/StompHandler.java
  src/main/java/roomit/main/global/config/chat/WebSocketConfig.java
  src/test/java/roomit/main/domain/chat/service/ChatServiceIntegrationTest.java
Labels: 🔨 Refactor

#183 Feature/#149 notification
  http/sub.http
  src/main/java/roomit/main/domain/notification/entity/Notification.java
  src/main/java/roomit/main/domain/notification/repository/EmitterRepository.java
  src/main/java/roomit/main/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/global/recomend/RecommendationService.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
Labels: 🔨 Refactor

#181 Refactor/#180 reservation refactor
  src/main/java/roomit/main/domain/reservation/controller/ReservationController.java
  src/main/java/roomit/main/domain/reservation/dto/response/MyWorkPlaceReservationResponse.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/reservation/entity/ReservationState.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
Labels: 🔨 Refactor

#184 Feature/#149 notification
  http/sub.http
  src/main/java/roomit/main/domain/member/entity/Member.java
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationDto.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
Labels: 🔨 Refactor

#188 Refactor/#178 mentor 멘토링 적용
  build.gradle
  src/main/java/roomit/main/domain/chat/chatmessage/dto/ChatMessageRequest.java
  src/main/java/roomit/main/domain/chat/chatmessage/dto/ChatMessageResponse.java
  src/main/java/roomit/main/domain/chat/chatmessage/dto/ChatMessageSaveRequest.java
  src/main/java/roomit/main/domain/chat/chatmessage/entity/ChatMessage.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatMessageBatchProcessor.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/request/ChatRoomRequest.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/response/ChatRoomBusinessResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/response/ChatRoomDetailsDTO.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/response/ChatRoomMemberResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/response/ChatRoomResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/roomit/main/domain/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/roomit/main/domain/chat/chatroom/service/ChatRoomService.java
  src/main/java/roomit/main/domain/workplace/dto/request/WorkplaceRequest.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceAllResponse.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceDetailResponse.java
  src/main/java/roomit/main/domain/workplace/entity/Workplace.java
  src/main/java/roomit/main/domain/workplace/entity/value/Coordinate.java
  src/main/java/roomit/main/domain/workplace/repository/WorkplaceRepository.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/RedisConfig.java
  src/main/java/roomit/main/global/util/PointUtil.java
  src/test/java/roomit/main/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🔨 Refactor

#189 ✨ feat : 분산락,예약 스케줄링 추가
  src/main/java/roomit/main/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/domain/reservation/service/ReservationScheduler.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/domain/studyroom/repository/search/SearchStudyRoom.java
  src/main/java/roomit/main/domain/studyroom/repository/search/SearchStudyRoomImpl.java
  src/main/java/roomit/main/domain/studyroom/service/StudyRoomService.java
  src/main/java/roomit/main/global/config/RedissonConfig.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/controller/HealthCheckController.java
  src/main/java/roomit/main/global/rock/AopForTransaction.java
  src/main/java/roomit/main/global/rock/CustomSpringELParser.java
  src/main/java/roomit/main/global/rock/DistributedLock.java
  src/main/java/roomit/main/global/rock/DistributedLockAop.java
  src/main/java/roomit/main/global/token/config/JWTFilter.java
  src/test/java/roomit/main/domain/test/ReservationLockTest.java
Labels: ✨ Feature

#193 :wrench: BugFix : 시간 직렬화 수정, 채팅 구독 성공
  src/main/java/roomit/main/domain/chat/chatmessage/dto/ChatMessageResponse.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/chat/redis/service/RedisSubscriber.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceAllResponse.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceDetailResponse.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/RedisConfig.java
  src/main/java/roomit/main/global/config/chat/StompHandler.java
  src/main/java/roomit/main/global/config/chat/WebSocketConfig.java
  src/main/java/roomit/main/global/util/PointUtil.java
Labels: 🐞 BugFix

#196 Deploy/ CI/CD및 Docker설정
  .github/workflows/CI-CD.yml
  python-server/Dockerfile
  python-server/app.py
  python-server/collaborative_models/collaborative_model_10s.pkl
  python-server/collaborative_models/collaborative_model_20s.pkl
  python-server/collaborative_models/collaborative_model_30s.pkl
  python-server/collaborative_models/collaborative_model_40s.pkl
  python-server/docker-compose.yml
  python-server/requirements.txt
  src/main/java/roomit/main/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/roomit/main/domain/workplace/repository/WorkplaceRepository.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
Labels: 🐞 BugFix, 🌏 Deploy

#202 :recycle: refactor : 멘토링 수정사항 리팩토링
  src/main/java/roomit/main/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/roomit/main/domain/member/entity/Member.java
  src/main/java/roomit/main/domain/member/repository/MemberRepository.java
  src/main/java/roomit/main/domain/reservation/service/ReservationScheduler.java
  src/main/java/roomit/main/global/common/CommonToken.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/oauth2/config/CustomSuccessHandler.java
  src/main/java/roomit/main/global/oauth2/dto/KakaoResponse.java
  src/main/java/roomit/main/global/oauth2/dto/NaverResponse.java
  src/main/java/roomit/main/global/oauth2/dto/OAuth2Response.java
  src/main/java/roomit/main/global/oauth2/dto/Provider.java
  src/main/java/roomit/main/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/roomit/main/global/token/config/JWTFilter.java
  src/main/java/roomit/main/global/token/controller/LoginController.java
  src/main/java/roomit/main/global/token/service/TokenService.java
Labels: 🔨 Refactor

#203 Refactor/ 사업장 및 거리계산 좌표 수정
  .github/workflows/SonarQube.yml
  src/main/java/roomit/main/domain/studyroom/controller/StudyRoomController.java
  src/main/java/roomit/main/domain/workplace/repository/WorkplaceRepository.java
  src/main/java/roomit/main/domain/workplace/repository/search/WorkplaceSearch.java
  src/main/java/roomit/main/domain/workplace/repository/search/WorkplaceSearchImpl.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
Labels: 🔨 Refactor

#209 Refactor/207 refactor 멘토링 리팩토링 & 채팅메시지 시간 형식 변환
  build.gradle
  src/main/java/roomit/main/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/roomit/main/domain/chat/chatmessage/dto/ChatMessageRequest.java
  src/main/java/roomit/main/domain/chat/chatmessage/dto/ChatMessageSaveRequest.java
  src/main/java/roomit/main/domain/chat/chatmessage/dto/request/ChatMessageRequest.java
  src/main/java/roomit/main/domain/chat/chatmessage/dto/request/ChatMessageSaveRequest.java
  src/main/java/roomit/main/domain/chat/chatmessage/dto/response/ChatMessageResponse.java
  src/main/java/roomit/main/domain/chat/chatmessage/entity/ChatMessage.java
  src/main/java/roomit/main/domain/chat/chatmessage/entity/SenderType.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/response/ChatRoomBusinessResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/response/ChatRoomMemberResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/dto/response/ChatRoomResponse.java
  src/main/java/roomit/main/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/roomit/main/global/config/RedisConfig.java
  src/main/java/roomit/main/global/util/BumblebeeStringUtil.java
Labels: 🔨 Refactor

#211 ✨ Feat : 하이브리드 필터링 기능 구현
  src/main/java/roomit/main/domain/workplace/controller/WorkplaceRecommendationController.java
  src/main/java/roomit/main/domain/workplace/dto/request/RecommendationResponse.java
  src/main/java/roomit/main/domain/workplace/dto/request/RecommendationResponseWrapper.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceRecommendResponse.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceRecommendationService.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/main/java/roomit/main/global/recomend/RecommendationService.java
  src/main/java/roomit/main/global/token/config/JWTFilter.java
Labels: ✨ Feature

#213 Fix/#210 fix workplace bugfix & chatting dynamic subscribe
  src/main/java/roomit/main/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/chat/redis/service/RedisSubscriber.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/chat/StompHandler.java
  src/main/java/roomit/main/global/util/PointUtil.java
Labels: 🐞 BugFix, 🔨 Refactor

#214 fix workplace bugfix & chatting dynamic subscribe
  src/main/java/roomit/main/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/chat/redis/service/RedisSubscriber.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/chat/StompHandler.java
  src/main/java/roomit/main/global/util/PointUtil.java
Labels: 🐞 BugFix, 🔨 Refactor

#216 Fix/#210 fix chat bugfix
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/chat/redis/service/RedisSubscriber.java
  src/main/java/roomit/main/global/config/RedisConfig.java
Labels: 🐞 BugFix

#219 Fix/#210 fix workplace bugfix
  src/main/java/roomit/main/domain/chat/chatmessage/entity/ChatMessage.java
  src/main/java/roomit/main/domain/studyroom/dto/response/FindPossibleStudyRoomResponse.java
  src/main/java/roomit/main/domain/studyroom/service/StudyRoomService.java
Labels: 🐞 BugFix, 🔨 Refactor

#220 Feature/#149 notification
  http/sub.http
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationDto.java
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationReservationDto.java
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationReservationMemberDto.java
  src/main/java/roomit/main/domain/notification/entity/MemberNotification.java
  src/main/java/roomit/main/domain/notification/entity/Notification.java
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
Labels: ✨ Feature

#221 Deploy Version 6
  http/sub.http
  src/main/java/roomit/main/domain/chat/chatmessage/entity/ChatMessage.java
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationDto.java
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationReservationDto.java
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationReservationMemberDto.java
  src/main/java/roomit/main/domain/notification/entity/MemberNotification.java
  src/main/java/roomit/main/domain/notification/entity/Notification.java
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/studyroom/dto/response/FindPossibleStudyRoomResponse.java
  src/main/java/roomit/main/domain/studyroom/service/StudyRoomService.java
Labels: 🌏 Deploy

#225 Feature/#149 notification
  http/sub.http
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationDto.java
  src/main/java/roomit/main/domain/notification/entity/ReviewNotification.java
  src/main/java/roomit/main/domain/notification/repository/ReviewNotificationRepository.java
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
Labels: 🔨 Refactor

#226 Deploy Version 8
  http/sub.http
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationDto.java
  src/main/java/roomit/main/domain/notification/entity/ReviewNotification.java
  src/main/java/roomit/main/domain/notification/repository/ReviewNotificationRepository.java
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
Labels: 📃 Docs

#191 Refactor/#182 reservation refactor
  src/main/java/roomit/main/domain/business/entity/Business.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/global/config/RedisConfig.java
Labels: 🔨 Refactor

#229 🗑️ Chore : 테스트 코드 수정
  http/sub.http
Labels: 🔨 Refactor

#231 Refactor/ 채팅방 사업장별로 수정 & workplace 사업자id 조회 응답값 변경
  src/main/java/roomit/main/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatMessageBatchProcessor.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/roomit/main/domain/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/roomit/main/domain/chat/chatroom/service/ChatRoomService.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceResponse.java
Labels: 🔨 Refactor

#233 Feature/#149 notification
  http/sub.http
  src/main/java/roomit/main/domain/notification/controller/NotificationController.java
  src/main/java/roomit/main/domain/notification/repository/EmitterRepository.java
  src/main/java/roomit/main/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/roomit/main/domain/notification/service/MemberNotificationService.java
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
Labels: 📃 Docs

#235 Refactor/#210 읽음 처리 보완
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/global/config/chat/StompHandler.java
  src/main/java/roomit/main/global/config/chat/WebSocketConfig.java
Labels: 🔨 Refactor

#237 sonarcube
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
  src/main/java/roomit/main/global/config/chat/StompHandler.java
Labels: 🔨 Refactor

#238 Fix/#210 fix 채팅오류 수정
  src/main/java/roomit/main/domain/chat/chatmessage/dto/response/ChatMessageResponse.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
Labels: 🐞 BugFix

#241 Feature/#149 notification
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
Labels: 🔨 Refactor

#242 Deploy Version 11
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
Labels: 🐞 BugFix

#243 Refactor/#210 채팅 레디스 키 변경
  src/main/java/roomit/main/domain/chat/chatmessage/dto/request/ChatMessageSaveRequest.java
  src/main/java/roomit/main/domain/chat/chatmessage/dto/response/ChatMessageResponse.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatMessageBatchProcessor.java
  src/main/java/roomit/main/domain/chat/chatmessage/service/ChatService.java
Labels: 🔨 Refactor

#244 Feature/#149 notification
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationDto.java
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationReservationDto.java
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationReservationMemberDto.java
  src/main/java/roomit/main/domain/notification/entity/Notification.java
  src/main/java/roomit/main/domain/notification/service/MemberNotificationService.java
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
Labels: 🐞 BugFix

#245 :recycle: Refactor : 결제 예약 상태 로직 수정
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
Labels: 🔨 Refactor

#248 :recycle: Refactor : 리뷰 url 수정
  src/main/java/roomit/main/domain/review/service/ReviewService.java
Labels: 🔨 Refactor

#249 Deploy Version 13
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
Labels: 🌏 Deploy

#250 Deploy Version 13버전 develop 브랜치로 clone
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
Labels: 🌏 Deploy

#252 Feature/#149 notification
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
Labels: 🐞 BugFix

#253 Deploy Version 14
  src/main/java/roomit/main/domain/notification/service/NotificationService.java
  src/main/java/roomit/main/domain/payments/Service/PaymentsService.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/domain/review/entity/Review.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/domain/workplace/repository/WorkplaceRepository.java
Labels: 🌏 Deploy

#255 Deploy Version 15
  http/sub.http
  python-server/docker-compose.yml
  python-server/k6-scripts/test-script.js
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationDto.java
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationReservationDto.java
  src/main/java/roomit/main/domain/notification/dto/ResponseNotificationReservationMemberDto.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
Labels: 🌏 Deploy

#256 Feature/#149 notification
  python-server/collaborative_models/collaborative_model_10s.pkl
  python-server/collaborative_models/collaborative_model_20s.pkl
  python-server/collaborative_models/collaborative_model_30s.pkl
  python-server/collaborative_models/collaborative_model_40s.pkl
  python-server/k6-scripts/test-script.js
Labels: 📃 Docs

#257 Deploy Version 16
  python-server/collaborative_models/collaborative_model_10s.pkl
  python-server/collaborative_models/collaborative_model_20s.pkl
  python-server/collaborative_models/collaborative_model_30s.pkl
  python-server/collaborative_models/collaborative_model_40s.pkl
  python-server/k6-scripts/test-script.js
Labels: 🌏 Deploy

#258 ♻️ Refactor : 특정 사업자 예약 확인 응답값 수정
  src/main/java/roomit/main/domain/reservation/dto/response/MyWorkPlaceReservationResponse.java
Labels: 🔨 Refactor

#259 Deploy Version 18
  src/main/java/roomit/main/domain/reservation/dto/response/MyWorkPlaceReservationResponse.java
Labels: 🌏 Deploy
