Repository prgrms-web-devcourse-final-project/WEB1_2_BUMBLEBEE_BE, pull requests merged in 2024-11, with the labels that each got.

#3 Github template 제작
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
Labels: ⚙ Setting

#8 📝 Docs : 패키지 구조 추가
  src/main/java/roomit/web1_2_bumblebee_be/Web12BumblebeeBeApplication.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/test.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/chat/test.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/chatroom/test.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/config/test.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/test.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/reservation/test.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/test.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/test.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/test.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/test.java
Labels: ⚙ Setting

#7 :sparkles: Feat: SpringSecurityConfig 추가
  src/main/java/roomit/web1_2_bumblebee_be/config/SpringSecurityConfig.java
Labels: ✨ Feature

#14 ✨ Feat : Member CRUD 기초 작업 완료
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/controller/ExceptionController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/controller/MemberController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/Member.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/Role.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/Sex.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/exception/MemberNotFound.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/exception/commonException.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/repository/MemberRepository.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/request/MemberRegisterRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/request/MemberUpdateRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/response/ErrorResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/response/MemberResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberService.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/controller/MemberControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberServiceTest.java
Labels: ✨ Feature

#17 ♻️ Refactor : Member 전체적인 수정
  build.gradle
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/controller/ExceptionController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/controller/MemberController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/Age.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/Member.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/exception/MemberNotFound.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/repository/MemberRepository.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/request/MemberRegisterRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/request/MemberUpdateRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/response/ErrorResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/response/MemberResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberService.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/QueryDSLConfig.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/StorageConfig.java
  src/main/java/roomit/web1_2_bumblebee_be/global/controller/ExceptionController.java
  src/main/java/roomit/web1_2_bumblebee_be/global/error/ErrorCode.java
  src/main/java/roomit/web1_2_bumblebee_be/global/error/ErrorResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/global/exception/commonException.java
  src/main/resources/application.properties
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/controller/MemberControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberServiceTest.java
Labels: 🔨 Refactor

#24 Feature / #13 business CRUD 틀 완성 <test단 제외>
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/controller/BusinessController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/entity/Business.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/exception/BusinessNotDelete.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/exception/BusinessNotFound.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/exception/BusinessNotModify.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/exception/BusinessNotRegister.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/repository/BusinessRepository.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/request/BusinessRegisterRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/request/BusinessUpdateRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/response/BusinessResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/service/BusinessService.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/test.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/Role.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/exception/commonException.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/test.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/SpringSecurityConfig.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/test.java
  src/main/java/roomit/web1_2_bumblebee_be/global/error/ErrorCode.java
Labels: ✨ Feature

#30 Feature / #18 spring security
  build.gradle
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/entity/Business.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/controller/MemberController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/CustomMemberDetails.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/response/ErrorResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/response/MemberResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/Role.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/service/CustomMemberDetailsService.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberService.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/SpringSecurityConfig.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/CorsMvcConfig.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/JWTFilter.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/JWTUtil.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/LoginFilter.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/controller/MemberControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberServiceTest.java
Labels: ✨ Feature

#36 Feature/#9 studyroom crud2
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/controller/StudyRoomController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/dto/request/CreateStudyRoomRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/dto/request/FindPossibleStudyRoomRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/dto/request/StudyRoomRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/dto/request/UpdateStudyRoomRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/dto/response/FindPossibleStudyRoomResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/dto/response/StudyRoomResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/entity/StudyRoom.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/exception/StudyRoomNotFound.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/repository/StudyRoomRepository.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/studyroom/service/StudyRoomService.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/dto/WorkplaceRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/JpaConfig.java
  src/main/java/roomit/web1_2_bumblebee_be/global/error/ErrorCode.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/studyroom/StudyRoomServiceTest.java
Labels: ✨ Feature

#38 Feature / #11 workplace entity 수정
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/repository/BusinessRepository.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/controller/WorkplaceController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/dto/WorkplaceRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/dto/WorkplaceResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/entity/Workplace.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/entity/value/ImageUrl.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/entity/value/WorkplaceAddress.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/entity/value/WorkplaceName.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/entity/value/WorkplacePhoneNumber.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/repository/WorkplaceRepository.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/SpringSecurityConfig.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🔨 Refactor

#40 Feature / #32 review crud 기초완성
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/Member.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberService.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/controller/ReviewController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/dto/request/ReviewRegisterRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/dto/request/ReviewSearch.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/dto/response/ReviewResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/entity/Review.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/exception/ReviewNotFound.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/exception/ReviewUpdateException.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/repository/ReviewRepository.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/service/ReviewService.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/JWTFilter.java
  src/main/java/roomit/web1_2_bumblebee_be/global/controller/DummyDataInitializer.java
  src/main/java/roomit/web1_2_bumblebee_be/global/error/ErrorCode.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberServiceTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feature

#41 :sparkles: feat : SpringSecurity 다중 로그인 구현
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/controller/BusinessController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/repository/BusinessRepository.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/response/CustomBusinessDetails.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/service/CustomBusinessDetailsService.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberService.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/JWTFilter.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/LoginFilter.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/controller/LoginController.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/dto/LoginRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/dto/LoginResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/token/BusinessAuthenticationToken.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/token/MemberAuthenticationToken.java
Labels: ✨ Feature

#42 Feature / #13 business Test코드 일부 작성 / 내부 클래스 추가
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/controller/BusinessController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/entity/value/BusinessEmail.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/entity/value/BusinessNickname.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/entity/value/BusinessNum.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/entity/value/BusinessPassword.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/repository/BusinessRepository.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/request/BusinessUpdateRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/service/BusinessService.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/business/controller/BusinessControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/business/service/BusinessServiceTest.java
Labels: ✨ Feature

#50 Refactor 사업장 정규표현식 수정
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/controller/WorkplaceController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/entity/value/WorkplaceAddress.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/entity/value/WorkplaceName.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/entity/value/WorkplacePhoneNumber.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/service/WorkplaceService.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🔨 Refactor

#53 ✨ feat : refresh토큰 구현
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/config/JWTFilter.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/config/JWTUtil.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/config/LoginFilter.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/config/LogoutFilter.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/controller/LoginController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/controller/ReissueController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/dto/LoginRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/dto/LoginResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/entity/RefreshEntity.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/repository/RefreshRepository.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/token/BusinessAuthenticationToken.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/token/token/MemberAuthenticationToken.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/JWTFilter.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/jwt/controller/LoginController.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/security/util/CookieUtil.java
Labels: ✨ Feature

#51 Feature/#47 feat member class
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/response/MemberResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/Member.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/value/MemberEmail.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/value/MemberNickname.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/value/MemberPassword.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/value/MemberPhoneNumber.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/repository/MemberRepository.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberService.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/controller/ReviewController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/dto/request/ReviewSearch.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/dto/response/CursorResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/dto/response/ReviewResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/repository/ReviewRepositoryImpl.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/controller/MemberControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberServiceTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feature

#57 ♻️ Refactor : ErrorCode 및 CommonException 수정
  src/main/java/roomit/web1_2_bumblebee_be/global/error/ErrorCode.java
  src/main/java/roomit/web1_2_bumblebee_be/global/exception/CommonException.java
Labels: 🔨 Refactor

#64 Refactor / #13 business 단 전체적인 리팩토링
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/controller/BusinessController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/dto/request/BusinessRegisterRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/dto/request/BusinessUpdateRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/dto/response/BusinessResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/entity/Business.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/exception/BusinessNotDelete.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/exception/BusinessNotFound.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/exception/BusinessNotModify.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/exception/BusinessNotRegister.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/service/BusinessService.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/business/service/CustomBusinessDetailsService.java
  src/main/java/roomit/web1_2_bumblebee_be/global/controller/ExceptionController.java
  src/main/java/roomit/web1_2_bumblebee_be/global/error/ErrorResponse.java
  src/test/java/roomit/web1_2_bumblebee_be/Web12BumblebeeBeApplicationTests.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/business/controller/BusinessControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/business/service/BusinessServiceTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/controller/MemberControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberServiceTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/review/service/ReviewServiceTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/studyroom/StudyRoomServiceTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🔨 Refactor

#65 Feature/#62 refactor workplace
  build.gradle
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/controller/WorkplaceController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/dto/WorkplaceRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/dto/WorkplaceResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/entity/Workplace.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/exception/WorkplaceInvalidRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/exception/WorkplaceNotDelete.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/exception/WorkplaceNotFound.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/exception/WorkplaceNotRegistered.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/exception/WorkspaceNotModified.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/web1_2_bumblebee_be/global/config/WebClientConfig.java
  src/main/java/roomit/web1_2_bumblebee_be/global/error/ErrorCode.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🔨 Refactor

#63 Refactor/60 member and review
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/controller/MemberController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/dto/response/MemberResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/entity/Member.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberService.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/controller/ReviewController.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/dto/request/ReviewRegisterRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/dto/response/CursorResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/dto/response/ReviewResponse.java
  src/main/java/roomit/web1_2_bumblebee_be/domain/review/service/ReviewService.java
  src/main/java/roomit/web1_2_bumblebee_be/global/error/ErrorCode.java
  src/main/java/roomit/web1_2_bumblebee_be/global/error/ErrorResponse.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/controller/MemberControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/member/service/MemberServiceTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/web1_2_bumblebee_be/domain/review/service/ReviewServiceTest.java
Labels: 🔨 Refactor

#75 ✨ feat : oauth 추가
  .github/workflows/CI.yml
  src/main/java/roomit/main/domain/business/dto/CustomBusinessDetails.java
  src/main/java/roomit/main/domain/member/dto/CustomMemberDetails.java
  src/main/java/roomit/main/domain/member/repository/MemberRepository.java
  src/main/java/roomit/main/domain/member/service/CustomMemberDetailsService.java
  src/main/java/roomit/main/domain/oauth2/config/CustomSuccessHandler.java
  src/main/java/roomit/main/domain/oauth2/dto/KakaoResponse.java
  src/main/java/roomit/main/domain/oauth2/dto/NaverResponse.java
  src/main/java/roomit/main/domain/oauth2/dto/OAuth2Response.java
  src/main/java/roomit/main/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/roomit/main/domain/token/config/JWTFilter.java
  src/main/java/roomit/main/domain/token/controller/LoginController.java
  src/main/java/roomit/main/global/config/security/CustomProviderManager.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/resources/static/logout.html
  src/test/java/roomit/main/Web12BumblebeeBeApplicationTests.java
Labels: ✨ Feature

#81 Feat/#69 reservation crud,refactor
  src/main/java/roomit/main/domain/reservation/controller/ReservationController.java
  src/main/java/roomit/main/domain/reservation/dto/request/CreateReservationRequest.java
  src/main/java/roomit/main/domain/reservation/dto/request/UpdateReservationRequest.java
  src/main/java/roomit/main/domain/reservation/dto/response/MyWorkPlaceReservationResponse.java
  src/main/java/roomit/main/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/reservation/repository/ReservationRepository.java
  src/main/java/roomit/main/domain/reservation/service/ReservationService.java
  src/main/java/roomit/main/domain/review/test.java
  src/main/java/roomit/main/domain/studyroom/controller/StudyRoomController.java
  src/main/java/roomit/main/domain/studyroom/dto/request/UpdateStudyRoomRequest.java
  src/main/java/roomit/main/domain/studyroom/dto/response/FindPossibleStudyRoomResponse.java
  src/main/java/roomit/main/domain/studyroom/repository/StudyRoomRepository.java
  src/main/java/roomit/main/domain/studyroom/service/StudyRoomService.java
Labels: ✨ Feature

#83 :white_check_mark: test: SpringSecurity JWT 테스트 코드
  src/main/java/roomit/main/domain/token/config/JWTFilter.java
  src/main/java/roomit/main/domain/token/config/LoginFilter.java
  src/main/java/roomit/main/domain/token/entity/RefreshEntity.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/test/java/roomit/main/Web12BumblebeeBeApplicationTests.java
  src/test/java/roomit/main/domain/jwt/WithMockCustomMemberSecurityContextFactory.java
  src/test/java/roomit/main/domain/jwt/mock/WithMockCustomMember.java
Labels: ✅ Test

#86 Feature/#39 feat chat
  .github/workflows/CI.yml
  build.gradle
  src/main/java/roomit/main/domain/chat/controller/ChatController.java
  src/main/java/roomit/main/domain/chat/dto/ChatMessageRequest.java
  src/main/java/roomit/main/domain/chat/dto/ChatMessageResponse.java
  src/main/java/roomit/main/domain/chat/entity/ChatMessage.java
  src/main/java/roomit/main/domain/chat/repository/ChatMessageRepository.java
  src/main/java/roomit/main/domain/chat/service/ChatService.java
  src/main/java/roomit/main/domain/chat/service/RedisPublisher.java
  src/main/java/roomit/main/domain/chat/service/RedisSubscriber.java
  src/main/java/roomit/main/domain/chat/test.java
  src/main/java/roomit/main/domain/chatroom/entity/ChatRoom.java
  src/main/java/roomit/main/domain/chatroom/repositoroy/ChatRoomRepository.java
  src/main/java/roomit/main/domain/chatroom/test.java
  src/main/java/roomit/main/global/config/RedisConfig.java
  src/main/java/roomit/main/global/config/ScheduledTasks.java
  src/main/java/roomit/main/global/config/WebSocketConfig.java
  src/test/java/roomit/main/domain/chat/RedisPubSubTest.java
  src/test/java/roomit/main/domain/chat/WebSocketTest.java
Labels: ✨ Feature

#89 Feature/#62 refactor workplace
  src/main/java/roomit/main/domain/workplace/controller/WorkplaceController.java
  src/main/java/roomit/main/domain/workplace/dto/WorkplaceRequest.java
  src/main/java/roomit/main/domain/workplace/dto/WorkplaceResponse.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/WebClientConfig.java
  src/main/java/roomit/main/global/controller/ExceptionController.java
  src/test/java/roomit/main/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🐞 BugFix

#91 Feature/#80 s3 presigned url
  build.gradle
  src/main/java/roomit/main/domain/member/controller/MemberController.java
  src/main/java/roomit/main/domain/review/controller/ReviewController.java
  src/main/java/roomit/main/domain/review/dto/request/ReviewRegisterRequest.java
  src/main/java/roomit/main/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/domain/token/config/JWTFilter.java
  src/main/java/roomit/main/domain/token/dto/LoginRequest.java
  src/main/java/roomit/main/global/config/AWSS3Config.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/java/roomit/main/global/controller/FileUploadController.java
  src/main/java/roomit/main/global/service/FileUploadService.java
  src/test/java/roomit/main/domain/member/controller/MemberControllerTest.java
  src/test/java/roomit/main/domain/member/service/MemberServiceTest.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/main/domain/review/service/ReviewServiceTest.java
Labels: 🔨 Refactor

#93 :sparkles: feat: SpringSecurity 경로별 인가 작업
  src/main/java/roomit/main/domain/member/entity/value/MemberPhoneNumber.java
  src/main/java/roomit/main/domain/oauth2/config/CustomSuccessHandler.java
  src/main/java/roomit/main/domain/oauth2/controller/Oauth2Controller.java
  src/main/java/roomit/main/domain/oauth2/dto/KakaoResponse.java
  src/main/java/roomit/main/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/roomit/main/domain/studyroom/controller/StudyRoomController.java
  src/main/java/roomit/main/domain/token/config/JWTFilter.java
  src/main/java/roomit/main/domain/token/controller/LoginController.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/main/resources/static/logout.html
Labels: ✨ Feature

#98 :recycle: refactor : member 리팩토링
  src/main/java/roomit/main/domain/business/dto/response/BusinessResponse.java
  src/main/java/roomit/main/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/roomit/main/domain/member/entity/Member.java
  src/main/java/roomit/main/domain/member/service/MemberService.java
  src/main/java/roomit/main/domain/oauth2/service/CustomOAuth2UserService.java
  src/test/java/roomit/main/domain/member/controller/MemberControllerTest.java
  src/test/java/roomit/main/domain/member/service/MemberServiceTest.java
Labels: 🔨 Refactor

#101 Feature/#62 refactor workplace
  src/main/java/roomit/main/domain/workplace/controller/WorkplaceController.java
  src/main/java/roomit/main/domain/workplace/dto/reponse/WorkplaceGetRequest.java
  src/main/java/roomit/main/domain/workplace/dto/reponse/WorkplaceRequest.java
  src/main/java/roomit/main/domain/workplace/dto/request/WorkplaceGetResponse.java
  src/main/java/roomit/main/domain/workplace/dto/request/WorkplaceResponse.java
  src/main/java/roomit/main/domain/workplace/entity/Workplace.java
  src/main/java/roomit/main/domain/workplace/entity/value/Coordinate.java
  src/main/java/roomit/main/domain/workplace/repository/WorkplaceRepository.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/test/java/roomit/main/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: ✨ Feature

#103 Setting /#96 datasql 생성
  .gitignore
  sonar-project.properties
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: 📃 Docs, ✅ Test

#105 Feature/#62 refactor workplace 사업장 생성 시 스터디룸도 함께 생성
  src/main/java/roomit/main/domain/token/config/JWTFilter.java
  src/main/java/roomit/main/domain/workplace/controller/WorkplaceController.java
  src/main/java/roomit/main/domain/workplace/dto/request/WorkplaceGetRequest.java
  src/main/java/roomit/main/domain/workplace/dto/request/WorkplaceRequest.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceGetResponse.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceResponse.java
  src/main/java/roomit/main/domain/workplace/entity/Workplace.java
  src/main/java/roomit/main/domain/workplace/repository/WorkplaceRepository.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/main/domain/review/service/ReviewServiceTest.java
  src/test/java/roomit/main/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🔨 Refactor

#107 BugFix : 사업장 생성 시 스터디룸 등록 오류 시 예외처리
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/test/java/roomit/main/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🐞 BugFix

#114 Refactor/#109 review refactor
  src/main/java/roomit/main/domain/member/entity/Member.java
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/main/java/roomit/main/domain/review/controller/ReviewController.java
  src/main/java/roomit/main/domain/review/dto/request/ReviewRegisterRequest.java
  src/main/java/roomit/main/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/roomit/main/domain/review/dto/response/ReviewResponse.java
  src/main/java/roomit/main/domain/review/entity/Review.java
  src/main/java/roomit/main/domain/review/repository/ReviewRepository.java
  src/main/java/roomit/main/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/roomit/main/domain/review/service/ReviewService.java
  src/main/java/roomit/main/domain/workplace/entity/Workplace.java
  src/main/java/roomit/main/global/error/ErrorCode.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/main/domain/review/service/ReviewServiceTest.java
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🔨 Refactor

#116 Refactor/#113 refactor workplace 사업장 리팩토링
  src/main/java/roomit/main/domain/workplace/controller/WorkplaceController.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceAllResponse.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceBusinessResponse.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceDetailResponse.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceGetResponse.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceResponse.java
  src/main/java/roomit/main/domain/workplace/entity/Workplace.java
  src/main/java/roomit/main/domain/workplace/repository/WorkplaceRepository.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/test/java/roomit/main/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🔨 Refactor

#119 :wrench: bugfix : reservation enum bugfix
  src/main/java/roomit/main/domain/reservation/entity/Reservation.java
  src/test/java/roomit/main/domain/review/controller/ReviewControllerTest.java
  src/test/java/roomit/main/domain/review/service/ReviewServiceTest.java
Labels: 🐞 BugFix

#126 Refactor/#113 refactor workplace
  src/main/java/roomit/main/domain/token/config/JWTFilter.java
  src/main/java/roomit/main/domain/workplace/controller/WorkplaceController.java
  src/main/java/roomit/main/domain/workplace/dto/request/WorkplaceGetRequest.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceAllResponse.java
  src/main/java/roomit/main/domain/workplace/dto/response/WorkplaceDetailResponse.java
  src/main/java/roomit/main/domain/workplace/repository/WorkplaceRepository.java
  src/main/java/roomit/main/domain/workplace/service/WorkplaceService.java
  src/main/java/roomit/main/global/config/security/SpringSecurityConfig.java
  src/test/java/roomit/main/domain/workplace/controller/WorkplaceControllerTest.java
  src/test/java/roomit/main/domain/workplace/service/WorkplaceServiceTest.java
Labels: 🔨 Refactor
